import "../styles/globals.css";
import Head from "next/head";
import { useRouter } from "next/router";

import { AuthUserProvider } from "../contexts/authUserContext";
import Dashboard from "./dashboard";

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  console.log(router);
  return (
    <>
      <Head>
        <title>Egressos IFNMG Campus Salinas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/if_icon.png" />
      </Head>
      <AuthUserProvider>
        {router.asPath === "/dashboard" ? (
          <Dashboard>
            <Component {...pageProps} />
          </Dashboard>
        ) : (
          <Component {...pageProps} />
        )}
      </AuthUserProvider>
    </>
  );
}

export default MyApp;
