import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import History from "../components/history";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Egressos IFNMG Campus Salinas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/if_icon.png" />
      </Head>

      <main>
        <div className="top-0 h-screen bg-cover bg-[url('/bg_header.jpg')] bg-fixed border-b-4 border-primary">
          <NavBar />
          <div className="flex flex-col mt-60">
            <span
              className="flex font-extra-light text-white text-48 justify-center"
              style={{ fontWeight: 100 }}
            >
              Você vai em frente. A gente acompanha.
            </span>
            <div>
              <p className="flex text-center mt-6 text-white text-16 font-semibold justify-center">
                Queremos ser a ponte para seu crescimento pessoal e profissional.
                <br /> Sinta-se à vontade para compartilhar bons momentos e construir grandes ideias
                <br />
                conosco.
              </p>
            </div>
          </div>
        </div>
        <History />
      </main>

      <footer></footer>
    </div>
  );
}
