import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Egressos IFNMG Campus Salinas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/if_icon.png" />
      </Head>

      <main className="top-0 h-screen bg-cover bg-[url('/bg_header.jpg')]">
        <NavBar/>    
      </main>

      <footer >
        
      </footer>
    </div>
  )
}
